// ═══════════════════════════════════════════════════════════════════════════
//  PUBG Mobile Regional PAC
//  Generated by NetOps PUBG Script Generator
//  Author: Saeed Al Yazouri
//  Generated: 2026-06-22T08:31:06.820Z
// ═══════════════════════════════════════════════════════════════════════════
//  CONFIGURATION:
//    Enemy Team    : Saudi Arabia 🇸🇦 (SA)
//    My Team       : Jordan 🇯🇴 (JO)
//    Recruitment   : Jordan 🇯🇴 (JO)
//    Friend Search : Jordan 🇯🇴 (JO)
//    Proxy Provider: AUTO
// ═══════════════════════════════════════════════════════════════════════════

// ┌─────────────────────────────────────────────────────────────────────────┐
// │  SECTION 1: UTILITY FUNCTIONS                                         │
// └─────────────────────────────────────────────────────────────────────────┘

function now() { return new Date().getTime(); }

function containsAny(str, keywords) {
    if (!str || !keywords) return false;
    for (var i = 0; i < keywords.length; i++) {
        if (str.indexOf(keywords[i]) !== -1) return true;
    }
    return false;
}

function isIPv4(ip) {
    if (!ip) return false;
    var p = ip.split(".");
    if (p.length !== 4) return false;
    for (var i = 0; i < 4; i++) {
        var n = parseInt(p[i], 10);
        if (isNaN(n) || n < 0 || n > 255) return false;
    }
    return true;
}

function generateSessionId() {
    var c = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    var id = "";
    for (var i = 0; i < 12; i++) id += c.charAt(Math.floor(Math.random() * c.length));
    return id;
}

// ┌─────────────────────────────────────────────────────────────────────────┐
// │  SECTION 2: CONFIGURATION                                             │
// └─────────────────────────────────────────────────────────────────────────┘

var CFG = {
    VERSION: "1.0.0",
    MODE: "REGION_OPTIMIZED",
    
    // ── Ping Thresholds ──
    TARGET_PING: 3,
    EXCELLENT_PING: 5,
    GOOD_PING: 9,
    MAX_ACCEPTABLE_PING: 13,
    
    // ── Region Settings ──
    ENEMY_TEAM_COUNTRY: "SA",
    MY_TEAM_COUNTRY: "JO",
    RECRUITMENT_COUNTRY: "JO",
    FRIENDS_COUNTRY: "JO",
    
    FORCE_LOBBY: true,
    FORCE_MATCHMAKING: true,
    FORCE_SOCIAL: true,
    BLOCK_INTERNATIONAL: false,
    
    // ── Performance ──
    BURST_MODE: true,
    ANTI_THROTTLING: true,
    ENABLE_ML_PREDICTION: true,
    STRICT_EU_BLOCK: false,
    
    // ── DNS/Route Cache ──
    DNS_CACHE_TTL: 25000,
    ROUTE_CACHE_TTL: 180000,
    STICKY_TTL: 360000,
    
    SMART_RETRY: true,
    MAX_PROXY_CHAIN: 3,
    RETRY_MAX: 3
};

// ┌─────────────────────────────────────────────────────────────────────────┐
// │  SECTION 3: PROXY SERVERS                                             │
// └─────────────────────────────────────────────────────────────────────────┘

var ORANGE_ULTRA_1 = "PROXY 94.127.211.6:20001";
var ZAIN_ULTRA_1 = "PROXY 109.237.193.187:80";
var UMNIAH_ULTRA_1 = "PROXY 212.35.85.26:80";
var ORANGE_PLAT_1 = "PROXY 149.200.136.6:443";
var ZAIN_PLAT_1 = "PROXY 79.173.192.10:8080";
var SOCIAL_ORANGE_1 = "PROXY 46.185.128.5:3128";
var SOCIAL_ZAIN_1 = "PROXY 176.29.0.10:8080";
var SOCIAL_UMNIAH_1 = "PROXY 82.212.64.10:3128";
var ORANGE_IRBID_1 = "PROXY 46.185.176.5:8080";
var ZAIN_IRBID_1 = "PROXY 79.173.240.10:3128";

// ┌─────────────────────────────────────────────────────────────────────────┐
// │  SECTION 4: IP RANGES BY COUNTRY (Live Data)                          │
// └─────────────────────────────────────────────────────────────────────────┘

// ── Saudi Arabia 🇸🇦 (9 ranges) ──
var IP_SA = [
    { ip: "51.252.0.0", mask: "255.254.0.0" },
    { ip: "54.185.0.0", mask: "255.255.0.0" },
    { ip: "86.51.0.0", mask: "255.255.0.0" },
    { ip: "188.50.0.0", mask: "255.254.0.0" },
    { ip: "37.224.0.0", mask: "255.254.0.0" },
    { ip: "51.253.0.0", mask: "255.255.0.0" },
    { ip: "5.103.0.0", mask: "255.255.0.0" },
    { ip: "55.0.0.0", mask: "255.0.0.0" },
    { ip: "95.135.0.0", mask: "255.255.0.0" }
];

function isInSA(ip) {
    if (!ip || !isIPv4(ip)) return false;
    for (var i = 0; i < IP_SA.length; i++) {
        if (isInNet(ip, IP_SA[i].ip, IP_SA[i].mask)) return true;
    }
    return false;
}

// ── Jordan 🇯🇴 (12 ranges) ──
var IP_JO = [
    { ip: "94.127.208.0", mask: "255.255.248.0" },
    { ip: "109.237.192.0", mask: "255.255.240.0" },
    { ip: "212.35.64.0", mask: "255.255.224.0" },
    { ip: "149.200.128.0", mask: "255.255.224.0" },
    { ip: "79.173.192.0", mask: "255.255.224.0" },
    { ip: "46.185.128.0", mask: "255.255.128.0" },
    { ip: "176.29.0.0", mask: "255.255.0.0" },
    { ip: "82.212.64.0", mask: "255.255.224.0" },
    { ip: "46.185.176.0", mask: "255.255.240.0" },
    { ip: "79.173.240.0", mask: "255.255.240.0" },
    { ip: "37.202.128.0", mask: "255.255.128.0" },
    { ip: "188.247.0.0", mask: "255.255.128.0" }
];

function isInJO(ip) {
    if (!ip || !isIPv4(ip)) return false;
    for (var i = 0; i < IP_JO.length; i++) {
        if (isInNet(ip, IP_JO[i].ip, IP_JO[i].mask)) return true;
    }
    return false;
}

// ┌─────────────────────────────────────────────────────────────────────────┐
// │  SECTION 5: PUBG MOBILE DOMAINS                                       │
// └─────────────────────────────────────────────────────────────────────────┘

var PUBG_DOMAINS = [
    "pubgmobile.com", "igamecj.com", "gcloudsdk.com",
    "tencentgames.com", "tencentcloud.com", "tencent-cloud.net",
    "sgameglobal.com", "midasbuy.com", "proximabeta.com",
    "leagueoflegends.com", "levelinfinite.com",
    "igame.qq.com", "hk.gcloudsdk.com"
];

var MATCHMAKING_KEYWORDS = ["match", "lobby", "queue", "battle", "arena", "combat"];
var SOCIAL_KEYWORDS = ["social", "friend", "crew", "clan", "chat", "message", "recruit"];
var SHOP_KEYWORDS = ["shop", "store", "payment", "midasbuy", "purchase"];

// ┌─────────────────────────────────────────────────────────────────────────┐
// │  SECTION 6: MAIN ROUTING FUNCTION                                     │
// └─────────────────────────────────────────────────────────────────────────┘

function FindProxyForURL(url, host) {
    // Skip plain hostnames and local
    if (isPlainHostName(host) || dnsDomainIs(host, ".local")) return "DIRECT";
    
    // Non-PUBG traffic - direct
    if (!containsAny(host, PUBG_DOMAINS) && !containsAny(url, PUBG_DOMAINS)) {
        return "DIRECT";
    }
    
    var hostIP = "";
    try { hostIP = dnsResolve(host) || ""; } catch(e) {}
    
    // ── Enemy Team Routing (Saudi Arabia) ──
    if (hostIP && isInSA(hostIP)) {
        // Route enemy-related traffic through optimized path
        return "PROXY 94.127.211.6:20001; DIRECT";
    }
    
    // ── My Team Routing (Jordan) ──
    if (hostIP && isInJO(hostIP)) {
        return "PROXY 94.127.211.6:20001; DIRECT";
    }
    
    // ── Matchmaking & Lobby ──
    if (containsAny(url, MATCHMAKING_KEYWORDS) || containsAny(url, ["lobby"])) {
        if (CFG.FORCE_MATCHMAKING) {
            return "PROXY 94.127.211.6:20001; DIRECT";
        }
    }
    
    // ── Social Features ──
    if (containsAny(url, SOCIAL_KEYWORDS) && CFG.FORCE_SOCIAL) {
        return "PROXY 212.35.85.26:80; DIRECT";
    }
    
    // ── Shop / Purchases ──
    if (containsAny(url, SHOP_KEYWORDS)) {
        return "DIRECT"; // Don't interfere with payments
    }
    
    // ── Default PUBG traffic ──
    return "PROXY 94.127.211.6:20001; DIRECT";
}
